### ISSUE TITLE
Build errors with CC3200SDK_1.1.0

### ISSUE THREAD

**Issue by davidrea** [keen/keen-cc3200#2]
When trying to build the library against version 1.1.0 of the CC3200 SDK, boilerplate.c generates a compiler error:
#137 struct "<unnamed>" has no field "EventData"

The structure indeed lacks an EventData field; "pSock->EventData" must now be replaced by "pSock->soketAsyncEvent.SockTxFailData", which has the same members (of interest to this function) as the old EventData field had.

**Comment by hex337** [comment]
@dacox can you take a look at this?

**Comment by davidrea** [comment]
Wow you made quick work of that! Thanks...

**Comment by dacox** [comment]
No worries, cheers!
