### ISSUE TITLE
Error when using add_event() function in main loop

### ISSUE THREAD

**Issue by PillarTech** [keen/keen-cc3200#5]
Hi,

I am trying to use the keen-cc3200 SDK to push events from the CC3200 to Keen.io.  I am receiving an error when using the add_event() function within the main loop of main.c.  If I use the function before main.c, the function will run and send the event to keen.io.  However, once I move the function inside of the main loop I receive the following error:

Can't find a source file at "D:/GIT/a0132167_sdk_1.1.0/source-1p1-rahul/simplelink/source/nonos.c" 
Locate the file or edit the source lookup path to include its location.

I am unsure why the add_event() gets held up only when it is in the main loop.  Also, could someone explain to me why the program has multiple errors compiling when I remove the "LOOP_FOREVER();" command at the bottom of main.c?  

Also, I would like to push an integer from my CC3200 to Keen.io instead of a const char.  Is this possible?

Here is a screenshot of the error I receive when while using add_event() inside of the main loop:

![keen_error](https://cloud.githubusercontent.com/assets/15008260/10352826/bfd0fa56-6d1f-11e5-9ff2-7486d641170c.JPG)

**Comment by dacox** [comment]
Hi, hopefully I can address your questions.
1. I do not get any errors when I move the logic of the `keen` function into the `main` function. However, it is important to note that you cannot return from the `main` function. 
2. I also do not have any compiler errors when I remove the `LOOP_FOREVER();` call. However, this call is used to make sure that the `main` function never returns. Basically, if `main` returns, bad things happen.
3. When you are sending data to Keen, you are sending a JSON object encoded in a buffer. That buffer is stored in a `char` array, but it can represent many different things.
   - The example in `README.md` is sending an Object that contains an integer.
     - `"motion_detections", "{\"cat\": 1}"`
   - If it were a string, not an integer, it would be encoded like `cat`
     - `"motion_detections", "{\"cat\": \"1\"}"`

The example application included with `keen-cc3200` is a fork of the following example project from Ti - [CC32xx_SSL_Demo_Application](http://processors.wiki.ti.com/index.php/CC32xx_SSL_Demo_Application)

Questions specific to the Ti CC3200 can be submitted to their help forum at [SimpleLink™ WiFi CC31xx/CC32xx Forum](https://e2e.ti.com/support/wireless_connectivity/f/968)

Hope that helps, Cheers!
